/* ============================================================
   reading-pane.js — Passage rendering, ellipsis gaps, expand/collapse
   ============================================================ */

function renderReadingPane() {
  const pane = document.getElementById('reading-pane');
  if (!pane || !App.data) return;
  pane.innerHTML = '';

  const chapters = App.data.chapters || [];
  const isFull = App.tiers[App.activeTierIndex].wordBudget >= App.data.totalWords;

  for (const chapter of chapters) {
    // Chapter heading — always visible
    const chHeading = document.createElement('h2');
    chHeading.className = 'chapter-heading';
    chHeading.id = `ch-${chapter.id}`;
    chHeading.textContent = chapter.title;
    pane.appendChild(chHeading);

    // Passages directly under chapter (before sections)
    if (chapter.passages && chapter.passages.length > 0) {
      renderPassageGroup(pane, chapter.passages, isFull);
    }

    // Sections
    if (chapter.sections) {
      for (const section of chapter.sections) {
        // Section heading — always visible
        const secHeading = document.createElement('h3');
        secHeading.className = 'section-heading';
        secHeading.id = `sec-${section.id}`;
        secHeading.textContent = section.title;
        pane.appendChild(secHeading);

        // Section passages
        if (section.passages && section.passages.length > 0) {
          renderPassageGroup(pane, section.passages, isFull);
        }
      }
    }
  }

  // AI disclosure at bottom
  const disclosure = document.createElement('div');
  disclosure.className = 'ai-disclosure';
  disclosure.innerHTML = `<span class="ai-icon">&#10022;</span> ${App.data.aiDisclosure || 'Passage selection scores and context notes were generated by AI. All displayed text is the original document.'}`;
  pane.appendChild(disclosure);
}

/* ---------- Render a group of passages with ellipsis gaps ---------- */

function renderPassageGroup(container, passages, isFull) {
  // Determine which passages are visible (included or expanded)
  const visible = [];
  const hidden = [];

  for (const p of passages) {
    if (isFull || App.includedPassageIds.has(p.id) || App.expandedPassageIds.has(p.id)) {
      visible.push(p);
    } else {
      hidden.push(p);
    }
  }

  // Walk through all passages in order, emitting visible ones
  // and ellipsis gaps for contiguous hidden runs
  let hiddenRun = [];

  for (let i = 0; i < passages.length; i++) {
    const p = passages[i];
    const isVisible = isFull || App.includedPassageIds.has(p.id) || App.expandedPassageIds.has(p.id);

    if (isVisible) {
      // Flush any accumulated hidden run as an ellipsis
      if (hiddenRun.length > 0) {
        renderEllipsisGap(container, hiddenRun);
        hiddenRun = [];
      }
      // Render the passage
      renderPassage(container, p);
    } else {
      hiddenRun.push(p);
    }
  }

  // Trailing hidden run
  if (hiddenRun.length > 0) {
    renderEllipsisGap(container, hiddenRun);
  }
}

/* ---------- Render a single passage ---------- */

function renderPassage(container, passage) {
  const div = document.createElement('div');
  div.className = 'passage';
  div.id = passage.id;

  let html = '';

  if (passage.paragraphNumber != null) {
    html += `<span class="passage-number">${passage.paragraphNumber}.</span>`;
  }

  let text = passage.text || '';

  // Render {{FN:N}} placeholders as inline clickable markers
  let textHtml = renderTextWithInlineFootnotes(text);

  html += `<span class="passage-text">${textHtml}</span>`;

  // Collapse button for expanded passages
  if (App.expandedPassageIds.has(passage.id) && !App.includedPassageIds.has(passage.id)) {
    html += ` <button class="collapse-btn" onclick="collapsePassage('${passage.id}')" title="Collapse this passage">&times;</button>`;
  }

  div.innerHTML = html;
  container.appendChild(div);

  // Render sidenotes after the passage is in the DOM so we can measure marker positions
  if (passage.footnoteMarkers && passage.footnoteMarkers.length > 0) {
    requestAnimationFrame(() => {
      renderSidenotesForPassage(div, passage);
    });
  }
}

function renderSidenotesForPassage(passageEl, passage) {
  const markers = passage.footnoteMarkers || [];
  if (markers.length === 0) return;

  let lastBottom = -Infinity;

  for (const fnNum of markers) {
    const fn = App.footnoteMap[fnNum];
    if (!fn) continue;

    const markerEl = passageEl.querySelector(`.fn-marker[data-fn="${fnNum}"]`);

    const sidenote = document.createElement('span');
    sidenote.className = 'sidenote';
    sidenote.setAttribute('data-fn', fnNum);
    sidenote.addEventListener('click', function() { toggleSidenote(this); });

    // Position vertically aligned with the marker, but avoid overlapping previous sidenotes
    if (markerEl) {
      const passageRect = passageEl.getBoundingClientRect();
      const markerRect = markerEl.getBoundingClientRect();
      let topOffset = markerRect.top - passageRect.top;
      if (topOffset < lastBottom) {
        topOffset = lastBottom;
      }
      sidenote.style.top = topOffset + 'px';
      // Estimate sidenote height for stacking (will refine after render)
      lastBottom = topOffset + 60;
    }

    const cleanText = cleanNbsp(fn.text || '');
    const briefText = truncateSidenote(cleanText, 120);

    let innerHtml = `<span class="sidenote-number">${fnNum}</span>`;
    innerHtml += `<span class="sidenote-brief">${escapeHtml(briefText)}</span>`;

    if (fn.sourceTitle) {
      innerHtml += `<span class="sidenote-category">${escapeHtml(fn.sourceTitle)}</span>`;
    } else if (fn.category) {
      innerHtml += `<span class="sidenote-category">${formatCategory(fn.category)}</span>`;
    }

    // Detail section (shown on click)
    let detailHtml = '';
    if (cleanText.length > 120) {
      detailHtml += `<div class="fn-text">${escapeHtml(cleanText)}</div>`;
    }
    if (fn.bibleRef && fn.bibleText) {
      detailHtml += `<div class="fn-bible-text">${escapeHtml(fn.bibleRef)}: ${escapeHtml(fn.bibleText)}</div>`;
    }
    if (detailHtml) {
      innerHtml += `<div class="sidenote-full">${detailHtml}</div>`;
    }

    innerHtml += `<button class="sidenote-close" onclick="event.stopPropagation(); closeSidenote(this)">&times;</button>`;

    sidenote.innerHTML = innerHtml;
    passageEl.appendChild(sidenote);
  }
}

function cleanNbsp(str) {
  return str.replace(/&nbsp;/g, ' ').replace(/ /g, ' ').replace(/\{\{FN:\d+\}\}/g, '');
}

function renderTextWithInlineFootnotes(text) {
  // Text now contains safe inline HTML (<i>, <em>, <a>, <sup>) from the parser.
  // Replace {{FN:N}} placeholders with clickable marker spans.
  // Do NOT escape — the HTML is pre-sanitized by the parser.
  return text.replace(/\{\{FN:(\d+)\}\}/g, (_, n) =>
    `<span class="fn-marker" data-fn="${n}" onclick="handleFootnoteClick(${n})">[${n}]</span>`
  );
}

function truncateSidenote(str, maxLen) {
  if (!str) return '';
  if (str.length <= maxLen) return str;
  return str.substring(0, maxLen).replace(/\s+\S*$/, '') + '…';
}

function formatCategory(cat) {
  if (!cat) return '';
  return cat.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}

/* ---------- Render an ellipsis gap ---------- */

function renderEllipsisGap(container, hiddenPassages) {
  if (hiddenPassages.length === 0) return;

  const totalWords = hiddenPassages.reduce((sum, p) => sum + (p.wordCount || 0), 0);
  const readTime = estimateReadingTime(totalWords);

  // Use contextNote from the first passage that has one, or generate a summary
  let contextLabel = '';
  for (const p of hiddenPassages) {
    if (p.contextNote) {
      contextLabel = truncate(p.contextNote, 60);
      break;
    }
  }
  if (!contextLabel && hiddenPassages.length === 1) {
    // Try to use first few words of the passage as a hint
    const txt = hiddenPassages[0].text || '';
    contextLabel = truncate(txt, 50);
  } else if (!contextLabel) {
    contextLabel = `${hiddenPassages.length} paragraph${hiddenPassages.length > 1 ? 's' : ''}`;
  }

  const gap = document.createElement('div');
  gap.className = 'ellipsis-gap';

  // Create a unique ID for this gap
  const gapId = `gap-${hiddenPassages[0].id}`;
  gap.id = gapId;

  const toggleBtn = document.createElement('button');
  toggleBtn.className = 'ellipsis-toggle';
  toggleBtn.innerHTML = `<span class="ellipsis-dots">&middot;&middot;&middot;</span><span class="ellipsis-label">${readTime} &middot; ${escapeHtml(contextLabel)}</span>`;

  // Click to show AI context note and expand option
  toggleBtn.addEventListener('click', () => {
    showEllipsisDetail(gap, hiddenPassages, readTime);
  });

  gap.appendChild(toggleBtn);
  container.appendChild(gap);
}

/* ---------- Ellipsis Detail (AI note + expand) ---------- */

function showEllipsisDetail(gapEl, hiddenPassages, readTime) {
  // Check if already showing detail
  if (gapEl.querySelector('.ai-context-note')) return;

  // Remove the toggle button
  const toggle = gapEl.querySelector('.ellipsis-toggle');
  if (toggle) toggle.style.display = 'none';

  const note = document.createElement('div');
  note.className = 'ai-context-note';

  // Get context note text
  let contextText = '';
  for (const p of hiddenPassages) {
    if (p.contextNote) {
      contextText = p.contextNote;
      break;
    }
  }
  if (!contextText) {
    // Generate a fallback from passage text
    if (hiddenPassages.length === 1) {
      contextText = truncate(hiddenPassages[0].text || '', 200);
    } else {
      contextText = `${hiddenPassages.length} paragraphs covering approximately ${readTime} of reading.`;
    }
  }

  let html = `<span class="ai-icon">&#10022;</span>`;
  html += `<p class="ai-text">${escapeHtml(contextText)}</p>`;

  if (hiddenPassages.length === 1) {
    html += `<button class="show-passage-btn" onclick="expandFromGap('${hiddenPassages[0].id}')">Show passage (${readTime} reading)</button>`;
  } else {
    // Show individual expand buttons or an "expand all" button
    html += `<button class="show-passage-btn" onclick="expandMultipleFromGap('${gapEl.id}', [${hiddenPassages.map(p => `'${p.id}'`).join(',')}])">Show all ${hiddenPassages.length} passages (${readTime})</button>`;

    // Also show individual paragraph controls if more than one
    if (hiddenPassages.length <= 5) {
      for (const p of hiddenPassages) {
        const pTime = estimateReadingTime(p.wordCount || 0);
        const pLabel = p.paragraphNumber != null ? `#${p.paragraphNumber}` : p.id;
        html += ` <button class="show-passage-btn" style="margin-top:4px;margin-left:4px;" onclick="expandFromGap('${p.id}')">Show ${pLabel} (${pTime})</button>`;
      }
    }
  }

  // Add a close/hide button
  html += ` <button class="collapse-btn" style="margin-left:8px;" onclick="hideEllipsisDetail(this)" title="Close">&times;</button>`;

  note.innerHTML = html;
  gapEl.appendChild(note);
}

window.hideEllipsisDetail = function(btnEl) {
  const gapEl = btnEl.closest('.ellipsis-gap');
  const note = gapEl.querySelector('.ai-context-note');
  if (note) note.remove();
  const toggle = gapEl.querySelector('.ellipsis-toggle');
  if (toggle) toggle.style.display = '';
};

/* Global functions called from onclick */
window.expandFromGap = function(passageId) {
  expandPassage(passageId);
};

window.expandMultipleFromGap = function(gapId, passageIds) {
  for (const id of passageIds) {
    App.expandedPassageIds.add(id);
    const p = App.allPassages.find(x => x.id === id);
    if (p) App.expandedWords += (p.wordCount || 0);
  }
  updateTierStatus();
  renderReadingPane();
  renderTOC();
};

/* ---------- Utilities ---------- */

function escapeHtml(str) {
  const div = document.createElement('div');
  div.textContent = str;
  return div.innerHTML;
}

function truncate(str, maxLen) {
  if (!str) return '';
  str = str.replace(/\{\{FN:\d+\}\}/g, '');
  if (str.length <= maxLen) return str;
  return str.substring(0, maxLen).replace(/\s+\S*$/, '') + '...';
}
